import { SnapletClient } from "@snaplet/seed";

// You can use @snaplet/copycat to generate fake data for a field, for example:
// ```
// await snaplet.users([{ email: ({ seed }) => copycat.email(seed) }])
// ```
// More on this in our docs: https://docs.snaplet.dev/core-concepts/seed#inside-the-snapletseed-workflow
import { copycat } from "@snaplet/copycat";

// This is a basic example generated by Snaplet to start you off, check out the docs for where to go from here
// * For more on getting started with @snaplet/seed: https://docs.snaplet.dev/getting-started/quick-start/seed
// * For a more detailed reference: https://docs.snaplet.dev/core-concepts/seed

const snaplet = new SnapletClient({
  dryRun: process.env.DRY !== "0",
});

// Clears all existing data in the database, but keep the structure
await snaplet.$resetDatabase();

await snaplet.users(
  (x) =>
    x(6, (index) => ({
      profiles: [
        {
          email: ({ $store }) => $store.users![index].email!,
          first_name: ({ seed }) => copycat.firstName(seed),
          last_name: ({ seed }) => copycat.lastName(seed),
          full_name: ({ seed }) => copycat.fullName(seed),
        },
      ],
    })),
  { connect: true }
);

const tripsStore = await snaplet.trips([
  {
    destination_name: "Barcelona",
    description: "Visit the famous basilica",
    trips_profiles: [
      { profile_id: snaplet.$store.profiles![0].id },
      { profile_id: snaplet.$store.profiles![1].id },
    ],
  },
  {
    destination_name: "Paris",
    description: "Iconic landmark with stunning views",
    trips_profiles: [
      { profile_id: snaplet.$store.profiles![0].id },
      { profile_id: snaplet.$store.profiles![2].id },
    ],
  },
  {
    destination_name: "Amsterdam",
    description: "Art museum dedicated to Vincent van Gogh",
    trips_profiles: [{ profile_id: snaplet.$store.profiles![1].id }],
  },
]);

await snaplet.activites([
  {
    title: "Sagrada Familia",
    description: "Visit the famous basilica",
    address: "Carrer de Mallorca, 401, 08013 Barcelona, Spain",
    image_path: "segrada_familia.jpg",
    done: ({ seed }) => copycat.bool(seed),
    trip_id: tripsStore.trips![0].id,
  },
  {
    title: "Park Güell",
    description: "Explore the colorful park",
    address: "08024 Barcelona, Spain",
    image_path: "park_guell.jpg",
    done: ({ seed }) => copycat.bool(seed),
    trip_id: tripsStore.trips![0].id,
  },
  {
    title: "Eiffel Tower",
    description: "Iconic landmark with stunning views",
    address: "Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France",
    image_path: "eiffel_tower.jpg",
    done: ({ seed }) => copycat.bool(seed),
    trip_id: tripsStore.trips![1].id,
  },
  {
    title: "Louvre Museum",
    description: "Home to thousands of works of art",
    address: "Rue de Rivoli, 75001 Paris, France",
    image_path: "louvre_museum.jpg",
    done: ({ seed }) => copycat.bool(seed),
    trip_id: tripsStore.trips![1].id,
  },
  {
    title: "Van Gogh Museum",
    description: "Art museum dedicated to Vincent van Gogh",
    address: "Museumplein 6, 1071 DJ Amsterdam, Netherlands",
    image_path: "van_gogh_museum.jpg",
    done: ({ seed }) => copycat.bool(seed),
    trip_id: tripsStore.trips![2].id,
  },
  {
    title: "Anne Frank House",
    description: "Historical museum about Anne Frank",
    address: "Prinsengracht 263-267, 1016 GV Amsterdam, Netherlands",
    image_path: "anne_frank_house.jpg",
    done: ({ seed }) => copycat.bool(seed),
    trip_id: tripsStore.trips![2].id,
  },
]);
