create table "public"."Activites" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text not null,
    "do_date" timestamp without time zone,
    "done" boolean not null default false,
    "address" text,
    "image_path" text
);


alter table "public"."Activites" enable row level security;

create table "public"."Profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."Profiles" enable row level security;

create table "public"."Trips" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "destination_name" text not null,
    "start_date" date not null,
    "end_date" date,
    "description" text
);


alter table "public"."Trips" enable row level security;

create table "public"."trips_activites" (
    "trip" bigint not null,
    "activity" uuid not null
);


alter table "public"."trips_activites" enable row level security;

create table "public"."trips_profiles" (
    "trip_id" bigint not null,
    "profile_id" uuid not null
);


alter table "public"."trips_profiles" enable row level security;

CREATE UNIQUE INDEX "Activites_pkey" ON public."Activites" USING btree (id);

CREATE UNIQUE INDEX "Profiles_pkey" ON public."Profiles" USING btree (id);

CREATE UNIQUE INDEX "Trips_pkey" ON public."Trips" USING btree (id);

CREATE UNIQUE INDEX trips_activites_pkey ON public.trips_activites USING btree (trip, activity);

CREATE UNIQUE INDEX trips_profiles_pkey ON public.trips_profiles USING btree (trip_id, profile_id);

alter table "public"."Activites" add constraint "Activites_pkey" PRIMARY KEY using index "Activites_pkey";

alter table "public"."Profiles" add constraint "Profiles_pkey" PRIMARY KEY using index "Profiles_pkey";

alter table "public"."Trips" add constraint "Trips_pkey" PRIMARY KEY using index "Trips_pkey";

alter table "public"."trips_activites" add constraint "trips_activites_pkey" PRIMARY KEY using index "trips_activites_pkey";

alter table "public"."trips_profiles" add constraint "trips_profiles_pkey" PRIMARY KEY using index "trips_profiles_pkey";

alter table "public"."Profiles" add constraint "Profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."Profiles" validate constraint "Profiles_id_fkey";

alter table "public"."trips_activites" add constraint "trips_activites_activity_fkey" FOREIGN KEY (activity) REFERENCES "Activites"(id) ON DELETE CASCADE not valid;

alter table "public"."trips_activites" validate constraint "trips_activites_activity_fkey";

alter table "public"."trips_activites" add constraint "trips_activites_trip_fkey" FOREIGN KEY (trip) REFERENCES "Trips"(id) ON DELETE CASCADE not valid;

alter table "public"."trips_activites" validate constraint "trips_activites_trip_fkey";

alter table "public"."trips_profiles" add constraint "trips_profiles_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES "Profiles"(id) ON DELETE CASCADE not valid;

alter table "public"."trips_profiles" validate constraint "trips_profiles_profile_id_fkey";

alter table "public"."trips_profiles" add constraint "trips_profiles_trip_id_fkey" FOREIGN KEY (trip_id) REFERENCES "Trips"(id) ON DELETE CASCADE not valid;

alter table "public"."trips_profiles" validate constraint "trips_profiles_trip_id_fkey";

grant delete on table "public"."Activites" to "anon";

grant insert on table "public"."Activites" to "anon";

grant references on table "public"."Activites" to "anon";

grant select on table "public"."Activites" to "anon";

grant trigger on table "public"."Activites" to "anon";

grant truncate on table "public"."Activites" to "anon";

grant update on table "public"."Activites" to "anon";

grant delete on table "public"."Activites" to "authenticated";

grant insert on table "public"."Activites" to "authenticated";

grant references on table "public"."Activites" to "authenticated";

grant select on table "public"."Activites" to "authenticated";

grant trigger on table "public"."Activites" to "authenticated";

grant truncate on table "public"."Activites" to "authenticated";

grant update on table "public"."Activites" to "authenticated";

grant delete on table "public"."Activites" to "service_role";

grant insert on table "public"."Activites" to "service_role";

grant references on table "public"."Activites" to "service_role";

grant select on table "public"."Activites" to "service_role";

grant trigger on table "public"."Activites" to "service_role";

grant truncate on table "public"."Activites" to "service_role";

grant update on table "public"."Activites" to "service_role";

grant delete on table "public"."Profiles" to "anon";

grant insert on table "public"."Profiles" to "anon";

grant references on table "public"."Profiles" to "anon";

grant select on table "public"."Profiles" to "anon";

grant trigger on table "public"."Profiles" to "anon";

grant truncate on table "public"."Profiles" to "anon";

grant update on table "public"."Profiles" to "anon";

grant delete on table "public"."Profiles" to "authenticated";

grant insert on table "public"."Profiles" to "authenticated";

grant references on table "public"."Profiles" to "authenticated";

grant select on table "public"."Profiles" to "authenticated";

grant trigger on table "public"."Profiles" to "authenticated";

grant truncate on table "public"."Profiles" to "authenticated";

grant update on table "public"."Profiles" to "authenticated";

grant delete on table "public"."Profiles" to "service_role";

grant insert on table "public"."Profiles" to "service_role";

grant references on table "public"."Profiles" to "service_role";

grant select on table "public"."Profiles" to "service_role";

grant trigger on table "public"."Profiles" to "service_role";

grant truncate on table "public"."Profiles" to "service_role";

grant update on table "public"."Profiles" to "service_role";

grant delete on table "public"."Trips" to "anon";

grant insert on table "public"."Trips" to "anon";

grant references on table "public"."Trips" to "anon";

grant select on table "public"."Trips" to "anon";

grant trigger on table "public"."Trips" to "anon";

grant truncate on table "public"."Trips" to "anon";

grant update on table "public"."Trips" to "anon";

grant delete on table "public"."Trips" to "authenticated";

grant insert on table "public"."Trips" to "authenticated";

grant references on table "public"."Trips" to "authenticated";

grant select on table "public"."Trips" to "authenticated";

grant trigger on table "public"."Trips" to "authenticated";

grant truncate on table "public"."Trips" to "authenticated";

grant update on table "public"."Trips" to "authenticated";

grant delete on table "public"."Trips" to "service_role";

grant insert on table "public"."Trips" to "service_role";

grant references on table "public"."Trips" to "service_role";

grant select on table "public"."Trips" to "service_role";

grant trigger on table "public"."Trips" to "service_role";

grant truncate on table "public"."Trips" to "service_role";

grant update on table "public"."Trips" to "service_role";

grant delete on table "public"."trips_activites" to "anon";

grant insert on table "public"."trips_activites" to "anon";

grant references on table "public"."trips_activites" to "anon";

grant select on table "public"."trips_activites" to "anon";

grant trigger on table "public"."trips_activites" to "anon";

grant truncate on table "public"."trips_activites" to "anon";

grant update on table "public"."trips_activites" to "anon";

grant delete on table "public"."trips_activites" to "authenticated";

grant insert on table "public"."trips_activites" to "authenticated";

grant references on table "public"."trips_activites" to "authenticated";

grant select on table "public"."trips_activites" to "authenticated";

grant trigger on table "public"."trips_activites" to "authenticated";

grant truncate on table "public"."trips_activites" to "authenticated";

grant update on table "public"."trips_activites" to "authenticated";

grant delete on table "public"."trips_activites" to "service_role";

grant insert on table "public"."trips_activites" to "service_role";

grant references on table "public"."trips_activites" to "service_role";

grant select on table "public"."trips_activites" to "service_role";

grant trigger on table "public"."trips_activites" to "service_role";

grant truncate on table "public"."trips_activites" to "service_role";

grant update on table "public"."trips_activites" to "service_role";

grant delete on table "public"."trips_profiles" to "anon";

grant insert on table "public"."trips_profiles" to "anon";

grant references on table "public"."trips_profiles" to "anon";

grant select on table "public"."trips_profiles" to "anon";

grant trigger on table "public"."trips_profiles" to "anon";

grant truncate on table "public"."trips_profiles" to "anon";

grant update on table "public"."trips_profiles" to "anon";

grant delete on table "public"."trips_profiles" to "authenticated";

grant insert on table "public"."trips_profiles" to "authenticated";

grant references on table "public"."trips_profiles" to "authenticated";

grant select on table "public"."trips_profiles" to "authenticated";

grant trigger on table "public"."trips_profiles" to "authenticated";

grant truncate on table "public"."trips_profiles" to "authenticated";

grant update on table "public"."trips_profiles" to "authenticated";

grant delete on table "public"."trips_profiles" to "service_role";

grant insert on table "public"."trips_profiles" to "service_role";

grant references on table "public"."trips_profiles" to "service_role";

grant select on table "public"."trips_profiles" to "service_role";

grant trigger on table "public"."trips_profiles" to "service_role";

grant truncate on table "public"."trips_profiles" to "service_role";

grant update on table "public"."trips_profiles" to "service_role";


