name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Copy environment variables
        run: cp .env.example .env
      - name: Lint check
        run: npm run lint
      - name: Build
        run: npm run build

  dependabot:
    name: "Dependabot auto merge"
    # if: github.actor == 'dependabot[bot]'
    needs: [build_test]
    runs-on: ubuntu-latest
    steps:
      - name: "Approve PR"
        run: gh pr review --approve ${{ env.PR_URL }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Auto-merge PR"
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge --auto -s ${{ env.PR_URL }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
